// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: time.proto

package TestRedis;

public final class TimeProto {
  private TimeProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface TimeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TestRedis.Time)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated int64 time = 1;</code>
     */
    java.util.List<java.lang.Long> getTimeList();
    /**
     * <code>repeated int64 time = 1;</code>
     */
    int getTimeCount();
    /**
     * <code>repeated int64 time = 1;</code>
     */
    long getTime(int index);
  }
  /**
   * Protobuf type {@code TestRedis.Time}
   */
  public static final class Time extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:TestRedis.Time)
      TimeOrBuilder {
    // Use Time.newBuilder() to construct.
    private Time(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Time(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Time defaultInstance;
    public static Time getDefaultInstance() {
      return defaultInstance;
    }

    public Time getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Time(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                time_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000001;
              }
              time_.add(input.readInt64());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                time_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                time_.add(input.readInt64());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          time_ = java.util.Collections.unmodifiableList(time_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return TestRedis.TimeProto.internal_static_TestRedis_Time_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return TestRedis.TimeProto.internal_static_TestRedis_Time_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TestRedis.TimeProto.Time.class, TestRedis.TimeProto.Time.Builder.class);
    }

    public static com.google.protobuf.Parser<Time> PARSER =
        new com.google.protobuf.AbstractParser<Time>() {
      public Time parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Time(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Time> getParserForType() {
      return PARSER;
    }

    public static final int TIME_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Long> time_;
    /**
     * <code>repeated int64 time = 1;</code>
     */
    public java.util.List<java.lang.Long>
        getTimeList() {
      return time_;
    }
    /**
     * <code>repeated int64 time = 1;</code>
     */
    public int getTimeCount() {
      return time_.size();
    }
    /**
     * <code>repeated int64 time = 1;</code>
     */
    public long getTime(int index) {
      return time_.get(index);
    }

    private void initFields() {
      time_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < time_.size(); i++) {
        output.writeInt64(1, time_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < time_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt64SizeNoTag(time_.get(i));
        }
        size += dataSize;
        size += 1 * getTimeList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static TestRedis.TimeProto.Time parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TestRedis.TimeProto.Time parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TestRedis.TimeProto.Time parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TestRedis.TimeProto.Time parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TestRedis.TimeProto.Time parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static TestRedis.TimeProto.Time parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static TestRedis.TimeProto.Time parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static TestRedis.TimeProto.Time parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static TestRedis.TimeProto.Time parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static TestRedis.TimeProto.Time parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(TestRedis.TimeProto.Time prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TestRedis.Time}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TestRedis.Time)
        TestRedis.TimeProto.TimeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return TestRedis.TimeProto.internal_static_TestRedis_Time_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return TestRedis.TimeProto.internal_static_TestRedis_Time_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                TestRedis.TimeProto.Time.class, TestRedis.TimeProto.Time.Builder.class);
      }

      // Construct using TestRedis.TimeProto.Time.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        time_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return TestRedis.TimeProto.internal_static_TestRedis_Time_descriptor;
      }

      public TestRedis.TimeProto.Time getDefaultInstanceForType() {
        return TestRedis.TimeProto.Time.getDefaultInstance();
      }

      public TestRedis.TimeProto.Time build() {
        TestRedis.TimeProto.Time result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public TestRedis.TimeProto.Time buildPartial() {
        TestRedis.TimeProto.Time result = new TestRedis.TimeProto.Time(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          time_ = java.util.Collections.unmodifiableList(time_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.time_ = time_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof TestRedis.TimeProto.Time) {
          return mergeFrom((TestRedis.TimeProto.Time)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(TestRedis.TimeProto.Time other) {
        if (other == TestRedis.TimeProto.Time.getDefaultInstance()) return this;
        if (!other.time_.isEmpty()) {
          if (time_.isEmpty()) {
            time_ = other.time_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureTimeIsMutable();
            time_.addAll(other.time_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        TestRedis.TimeProto.Time parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (TestRedis.TimeProto.Time) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<java.lang.Long> time_ = java.util.Collections.emptyList();
      private void ensureTimeIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          time_ = new java.util.ArrayList<java.lang.Long>(time_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated int64 time = 1;</code>
       */
      public java.util.List<java.lang.Long>
          getTimeList() {
        return java.util.Collections.unmodifiableList(time_);
      }
      /**
       * <code>repeated int64 time = 1;</code>
       */
      public int getTimeCount() {
        return time_.size();
      }
      /**
       * <code>repeated int64 time = 1;</code>
       */
      public long getTime(int index) {
        return time_.get(index);
      }
      /**
       * <code>repeated int64 time = 1;</code>
       */
      public Builder setTime(
          int index, long value) {
        ensureTimeIsMutable();
        time_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 time = 1;</code>
       */
      public Builder addTime(long value) {
        ensureTimeIsMutable();
        time_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 time = 1;</code>
       */
      public Builder addAllTime(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensureTimeIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, time_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 time = 1;</code>
       */
      public Builder clearTime() {
        time_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:TestRedis.Time)
    }

    static {
      defaultInstance = new Time(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:TestRedis.Time)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TestRedis_Time_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_TestRedis_Time_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ntime.proto\022\tTestRedis\"\024\n\004Time\022\014\n\004time\030" +
      "\001 \003(\003B\026\n\tTestRedisB\tTimeProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_TestRedis_Time_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TestRedis_Time_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_TestRedis_Time_descriptor,
        new java.lang.String[] { "Time", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
